/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberito.vistas;

import bomberito.accesoADatos.SiniestroData;
import bomberito.entidades.Siniestro;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melina
 */
public class HistorialDeSiniestros extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    
    SiniestroData controlSin=null;
    /**
     * Creates new form HistorialDeSiniestros
     */
    public HistorialDeSiniestros() {
        controlSin=new SiniestroData();
        modelo=new DefaultTableModel();
        initComponents();
        armarCabeceraTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Historial de Siniestros");

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTabla);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraTabla() {
        modelo.addColumn("ID");
        modelo.addColumn("Tipo");
        modelo.addColumn("X");
        modelo.addColumn("Y");
        modelo.addColumn("codBrigada");
        modelo.addColumn("Detalles");
        modelo.addColumn("Fecha Inicial");
        modelo.addColumn("Puntuacion");
        modelo.addColumn("Fecha Resolucion");
        modelo.addColumn("Activo");
        JTabla.setModel(modelo);
    }
    
    private void cargarTabla(){
        String activo;
        String punt;
        for (Siniestro cosa : controlSin.HistorialSin()) {
            String IdNomBri;
            if (cosa.getCodBrigada() != null) {
                IdNomBri = "[" + cosa.getCodBrigada().getIdBrigada() + "] " + cosa.getCodBrigada().getNombreBrigada();
            } else {
                // En caso que el codBrigada es null
                IdNomBri = "Sin brigada asignada";
            }
            if (cosa.isActivo()){
                activo="Si";
            }else{
                activo="No";
            }
            if (cosa.getPuntuacion()>0){
                punt=Integer.toString(cosa.getPuntuacion());
            }else{
                punt="Sin puntuacion";
            }
            
            modelo.addRow(new Object[]{
                cosa.getIdSiniestro(),
                cosa.getTipo(),
                cosa.getCoordX(),
                cosa.getCoordY(),
                IdNomBri,
                cosa.getDetalles(),
                cosa.getFechaSiniestro(),
                punt,
                cosa.getFechaResolucion(),
                activo
            });
        }
    }
    
}
